services:
  api:
    container_name: konnect
    ports:
      - "8000:80"
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
      REDIS_URL: "redis://redis:6379/0"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      RABBITMQ_URL: "amqp://konnect:konnect@rabbitmq:5672/"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: konnect-celery
    command: >
      uv run celery
      -A backend.celery_app:celery_app
      worker
      --loglevel=info
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: konnect
      RABBITMQ_DEFAULT_PASS: konnect
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pg_data:
  redis_data:
  es_data:
  rabbitmq_data: