"""users model corrected

Revision ID: 0c1125cd672f
Revises: d84d7603bff7
Create Date: 2026-08-26 19:53:37.310408

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c1125cd672f"
down_revision: str | Sequence[str] | None = "d84d7603bff7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.TEXT(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            sa.TEXT(),
            server_default=sa.text("'local'"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
