"""fix: issue with migrating to db

Revision ID: 17027f857912
Revises: 4e9fcf1fee57
Create Date: 2026-09-01 13:29:52.157650

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17027f857912"
down_revision: str | Sequence[str] | None = "4e9fcf1fee57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_profile",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.TEXT(), nullable=False),
        sa.Column("image", sa.TEXT(), nullable=True),
        sa.Column("business_licence", sa.TEXT(), nullable=True),
        sa.Column("phone_number", sa.TEXT(), nullable=False),
        sa.Column("rating", sa.FLOAT(), server_default=sa.text("3.0"), nullable=False),
        sa.Column(
            "report_count", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "verified", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("address", sa.VARCHAR(length=255), nullable=False),
        sa.Column("business_name", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vendor_profile_user_id"), "vendor_profile", ["user_id"], unique=True
    )
    op.drop_index(op.f("ix_user_profile_user_id"), table_name="user_profile")
    op.create_index(
        op.f("ix_user_profile_user_id"), "user_profile", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profile_user_id"), table_name="user_profile")
    op.create_index(
        op.f("ix_user_profile_user_id"), "user_profile", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_vendor_profile_user_id"), table_name="vendor_profile")
    op.drop_table("vendor_profile")
    # ### end Alembic commands ###
