"""fix review and report models

Revision ID: 27161cea665f
Revises: 5b7cbbe41d3f
Create Date: 2026-09-25 19:47:53.977467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27161cea665f"
down_revision: Union[str, Sequence[str], None] = "5b7cbbe41d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create the enum type in the database first
    report_status_enum = postgresql.ENUM(
        "pending", "approved", "dismissed", name="report_status"
    )
    report_status_enum.create(op.get_bind())

    op.add_column(
        "vendor_profile",
        sa.Column(
            "is_active", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.drop_column("vendor_profile", "report_count")
    op.add_column(
        "vendor_report",
        sa.Column("reviewed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )

    # 2. DROP the existing default constraint before changing types to avoid PostgreSQL mismatch errors
    op.execute("ALTER TABLE vendor_report ALTER COLUMN status DROP DEFAULT")

    # 3. Alter column type and safely cast existing text data into the new ENUM
    op.alter_column(
        "vendor_report",
        "status",
        existing_type=sa.TEXT(),
        type_=report_status_enum,
        existing_nullable=False,
        postgresql_using="status::report_status",
    )

    # 4. SET the new default value adapted for the Enum type
    op.execute(
        "ALTER TABLE vendor_report ALTER COLUMN status SET DEFAULT 'pending'::report_status"
    )

    op.create_unique_constraint(
        "uq_report_reporter_vendor", "vendor_report", ["reporter_id", "vendor_id"]
    )
    op.create_unique_constraint(
        "uq_review_buyer_vendor", "vendor_review", ["buyer_id", "vendor_id"]
    )
    op.create_check_constraint(
        "ck_review_rating_range", "vendor_review", "rating >= 1 AND rating <= 5"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_review_rating_range", "vendor_review", type_="check")
    op.drop_constraint("uq_review_buyer_vendor", "vendor_review", type_="unique")
    op.drop_constraint("uq_report_reporter_vendor", "vendor_report", type_="unique")

    # 1. Drop the Enum default before reverting to Text
    op.execute("ALTER TABLE vendor_report ALTER COLUMN status DROP DEFAULT")

    # 2. Revert column back to TEXT type
    report_status_enum = postgresql.ENUM(
        "pending", "approved", "dismissed", name="report_status"
    )
    op.alter_column(
        "vendor_report",
        "status",
        existing_type=report_status_enum,
        type_=sa.TEXT(),
        existing_nullable=False,
    )

    # 3. Restore the old Text default constraint
    op.execute(
        "ALTER TABLE vendor_report ALTER COLUMN status SET DEFAULT 'pending'::text"
    )

    op.drop_column("vendor_report", "reviewed_at")
    sa.Column(
        "report_count",
        sa.INTEGER(),
        server_default=sa.text("0"),
        autoincrement=False,
        nullable=False,
    )
    op.add_column(
        "vendor_profile",
        sa.Column(
            "report_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("vendor_profile", "is_active")

    # 4. Manually drop the enum type from the database
    report_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
