"""notification model

Revision ID: 30e842e9448d
Revises: 36c598ef7e15
Create Date: 2026-09-04 15:21:32.411078

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30e842e9448d"
down_revision: str | Sequence[str] | None = "36c598ef7e15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column(
            "notification_type",
            sa.TEXT(),
            server_default=sa.text("'INFO'"),
            nullable=True,
        ),
        sa.Column("action_url", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "is_read", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=True
    )
    op.drop_constraint(
        op.f("user_profile_user_id_fkey"), "user_profile", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_profile", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("vendor_profile_user_id_fkey"), "vendor_profile", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "vendor_profile", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendor_profile", type_="foreignkey")
    op.create_foreign_key(
        op.f("vendor_profile_user_id_fkey"),
        "vendor_profile",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "user_profile", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_profile_user_id_fkey"), "user_profile", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
