"""fix: issue with migrating with relationship fixed

Revision ID: 36c598ef7e15
Revises: f5b8ab936577
Create Date: 2026-09-01 13:57:26.313420

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "36c598ef7e15"
down_revision: str | Sequence[str] | None = "f5b8ab936577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
