"""user profile model revised

Revision ID: 4e9fcf1fee57
Revises: 099d6f7104f8
Create Date: 2026-09-01 11:18:59.657386

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e9fcf1fee57"
down_revision: str | Sequence[str] | None = "099d6f7104f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_profile_permission_level"),
        "user_profile",
        ["permission_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_profile_user_id"), "user_profile", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profile_user_id"), table_name="user_profile")
    op.drop_index(op.f("ix_user_profile_permission_level"), table_name="user_profile")
    # ### end Alembic commands ###
