"""notification model amended

Revision ID: 5a4b25edd053
Revises: 30e842e9448d
Create Date: 2026-09-04 15:28:47.799059

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a4b25edd053"
down_revision: str | Sequence[str] | None = "30e842e9448d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=True
    )
    # ### end Alembic commands ###
