"""fix vendor_profile

Revision ID: 5ae56b2ebb14
Revises: 5a4b25edd053
Create Date: 2026-09-07 23:46:56.125653

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae56b2ebb14"
down_revision: str | Sequence[str] | None = "5a4b25edd053"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor_profile", sa.Column("business_license", sa.TEXT(), nullable=True)
    )
    op.drop_column("vendor_profile", "business_licence")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor_profile",
        sa.Column("business_licence", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("vendor_profile", "business_license")
    # ### end Alembic commands ###
