"""review and reports models

Revision ID: 5b7cbbe41d3f
Revises: ffb0343ea31f
Create Date: 2026-09-18 10:12:25.150821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b7cbbe41d3f"
down_revision: Union[str, Sequence[str], None] = "ffb0343ea31f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_report",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=False),
        sa.Column(
            "status", sa.TEXT(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendor_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vendor_report_reporter_id"),
        "vendor_report",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_report_vendor_id"), "vendor_report", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_review",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("buyer_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendor_profile.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vendor_review_buyer_id"), "vendor_review", ["buyer_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_review_vendor_id"), "vendor_review", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_review_vendor_id"), table_name="vendor_review")
    op.drop_index(op.f("ix_vendor_review_buyer_id"), table_name="vendor_review")
    op.drop_table("vendor_review")
    op.drop_index(op.f("ix_vendor_report_vendor_id"), table_name="vendor_report")
    op.drop_index(op.f("ix_vendor_report_reporter_id"), table_name="vendor_report")
    op.drop_table("vendor_report")
    # ### end Alembic commands ###
