"""users model modification

Revision ID: b2a54b3fa74b
Revises: 0c1125cd672f
Create Date: 2026-08-26 21:19:42.412208

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b2a54b3fa74b"
down_revision: str | Sequence[str] | None = "0c1125cd672f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
