"""fix: issue with migrating with relationship

Revision ID: f5b8ab936577
Revises: 17027f857912
Create Date: 2026-09-01 13:51:23.552862

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f5b8ab936577"
down_revision: str | Sequence[str] | None = "17027f857912"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
