"""products model

Revision ID: ffb0343ea31f
Revises: 5ae56b2ebb14
Create Date: 2026-09-14 08:52:37.139163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffb0343ea31f"
down_revision: Union[str, Sequence[str], None] = "5ae56b2ebb14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("price", sa.FLOAT(), nullable=False),
        sa.Column(
            "discount", sa.INTEGER(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "in_stock", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("images", postgresql.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("category", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vendor_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_vendor_id"), "products", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_vendor_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
